apiVersion: v1
kind: Service
metadata:
  name: serving-service
spec:
  # Use LoadBalancer if running on a cloud provider and you want external access
  type: ClusterIP
  selector:
    app: serving
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
