dataset: "CIFAR10" # Using 10 digits dataset for classification.
data_dir: "./data"
batch_size: 64
num_epochs: 10
learning_rate: 0.001
num_classes: 10
pretrained: true
output_dir: "checkpoints"
model_filename: "cifar10_model.pth"
patience: 3 # Early stopping patience.